title: hy-push-state
email: mail@qwtel.com

description: >
  Turn web sites into web apps.
baseurl: /hy-push-state
url: https://qwtel.com

author:
  email: mail@qwtel.com
  social:
    github: https://github.com/qwtel/hy-push-state
    npm: https://www.npmjs.com/package/hy-push-state
    download: https://github.com/qwtel/hy-push-state/archive/v1.0.0-hydejack.4.zip

copyright: © 2017 Florian Klampfer

permalink: pretty

color: '#4fb1ba'
image:
  background: 'linear-gradient(to bottom,#193747 0%,#233e4c 30%,#3c929e 50%,#d5d5d4 70%,#cdccc8 100%)'
  overlay:    true

# Build settings
markdown: kramdown
theme: jekyll-theme-hydejack
plugins:
  - jekyll-default-layout
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-titles-from-headings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - package.json
  - package-lock.json
  - webpack.config.js
  - src
  - scripts
include:
  - LICENSE.md

defaults:
  - scope:
      path: doc/options.md
    values:
      menu: true
      order: 1
  - scope:
      path: doc/methods.md
    values:
      menu: true
      order: 2
  - scope:
      path: doc/events.md
    values:
      menu: true
      order: 3

titles_from_headings:
  strip_title: true
  collections: true

relative_links:
  collections: true

optional_front_matter:
  remove_originals: true

readme_index:
  remove_originals: true

data_social:
  github:
    name: GitHub
    icon: icon-github
  npm:
    name: npm
    icon: icon-npm
  download:
    name: Download
    icon: icon-box-add
